### ISSUE TITLE
反馈Android-RatioLayout问题

### ISSUE THREAD

**Issue by TCQQ** [amphiaraus/Android-RatioLayout#4]
你好，当前我设置heightRatio和widthRatio比例后，然后我将手机切换成横屏模式，正确的情况应该是heightRatio和widthRatio的值调换一下顺序，这样才能够适配横屏，但是当我切换横屏模式后它们没有被调换，导致横屏使用的比例是竖屏的比例，导致横屏无法适配，这种情况应该怎么做呢？

**Comment by amphiaraus** [comment]
我检查一下,将会发布修复版本.

**Comment by TCQQ** [comment]
好的，谢谢

**Comment by amphiaraus** [comment]
你好,留一下你的联系方式

**Comment by TCQQ** [comment]
看QQ
